version: "3.4"

services:
    mercure:
        image: dunglas/mercure
        environment:
            CORS_ALLOWED_ORIGINS: "http://localhost:8000"
            DEBUG: 1
            PUBLISHER_JWT_KEY: "!mySuperPublisherSecretKey!"
            SUBSCRIBER_JWT_KEY: "!mySuperSubscriberSecretKey!"
        expose:
            - "80"
        ports:
            - "5000:80"

    server:
        build: ./server
        working_dir: /var/www
        environment:
            APP_ENV: "dev"
            APP_DEBUG: 1
            WWW_USER: "1000"
        volumes:
            - "./server:/var/www"
        ports:
          - "8000:80"
        command: "bash -c 'usermod -u $${WWW_USER} www-data; . /etc/apache2/envvars; exec apache2 -D FOREGROUND'"

    client:
        image: "node:11"
        user: "node"
        working_dir: /home/node/app
        environment:
            NODE_USER: "1000"
        volumes:
            - ./client:/home/node/app
        ports:
            - "3000:3000"
            - "3001:3001"
        command: "bash -c 'usermod -u $${NODE_USER} node; yarn && yarn start'"
