overblog_graphql:
    definitions:
        schema:
            query: Query
            mutation: Mutation
            subscription: Subscription
            resolver_maps: [App\GraphQL\Resolver\SubscriptionResolverMap]
        mappings:
            types:
                -
                    type: graphql
                    dir: "%kernel.project_dir%/config/graphql/types"
                    suffix: ~
    security:
        handle_cors: true
